name: Run Tests

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Adjust to your Python version
    
    - name: Install project (editable) and dependencies
      run: |
            python -m pip install -e .
            python -m pip install --upgrade pip
            pip install pytest pandas
            pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/bucketize_sum_month_lags_test.py -v

    - name: Show suspicious requirements line
      run: |
        nl -ba requirements.txt | sed -n '28,34p'